### ISSUE TITLE
No matching export for import "Liminal"

### ISSUE THREAD

**Issue by gilbert** [barneycarroll/cascading-components#24]
Can't `import { Liminal } from 'mithril-machine-tools'`, needs to be [exported](https://github.com/barneycarroll/mithril-machine-tools/blob/dc6f7db574aecb64071113f4b31cc04a3e0cb0d8/index.js)

**Comment by barneycarroll** [comment]
Sorry, I missed this - [it works now](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvCLAB0oCcaACYAGSYkxQAvpzBtKWTgHIsEGgAs20ALRYM5eQJjKalSlDhSAOmhOwuzNvHpcAvKIwGYnEyaz4slAK60AFABNKci8cWnwAI0p-AE8SbhNOTgA3CBgAd0ROXwBKTlsAPk5kBMTOLF8pcK8aXTQpOOAS0s46AA8aAGFqOlpMqQAVSgBzIdh6ptLqcigIcgBrHMa0ZubLa1o8zgBCNbgbCcShEgmhbOPl0onkXZtOADI7g7LfPllBBqfE8Iw9vpo2DBoOByCDUZSUZjqOTRcYXFacDDhPa9aQQqE0aLKAAMsPhiRuKKkaPI0OUAEZcSsjp9nlJ5BS4lIABIwKBQShbKTZJ7cuGcAC650S-JMpxAZD2sHINFBQLwAA5EGSAGwgISCkAzNBzBAodDYXCIECyBRKKBEUggLxsKB4eQ1ZhwRAAemdPmYcyG+CoWGdJsU0AAAgAmfBY-AAFj9cgD5uI4pAGOYhpAcHISmYNDVJH1ODwNAw0DSAn8HgE3rgluttqN9pojpdbrQHq9PudBaLJfIlZD+DJ+GDzv8EDgNHbhagxbQpbeFctSZTo+isDV-KEQA)!
